# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ms0kupB85UOOkOpPrR-7HjfciG1rJiFV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

data = pd.read_csv("sample_data/sales.csv")
data['Order Date'] = pd.to_datetime(data['Order Date'])
data2 = data.groupby(['Item Type']).mean()
data2

data

model = LinearRegression()

X = pd.DataFrame(data2[['Unit Price']])
Y = pd.DataFrame(data2[['Total Profit']])

model.fit(X, Y)

model.coef_

model.intercept_

plt.figure(figsize = (10,8))
plt.scatter(data2['Unit Price'], data2['Total Profit'])
plt.plot(X, model.predict(X), color = 'red')

model.score(X, Y)

model.predict([[3500]])